print("H E L L O  ")
print(" E L L O   ")
print("E L L O   W")
print(" L L O   W ")
print("L L O   W O")
print(" L O   W O ")
print("L O   W O R")
print(" O   W O R ")
print("O   W O R L")
print("   W O R L ")
print("  W O R L D")